DROP TABLE IF EXISTS dogs;

CREATE TABLE dogs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  age INTEGER,
  weight TEXT
);


DROP TABLE IF EXISTS plants;

CREATE TABLE plants (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  type TEXT,
  sun TEXT
);

DROP TABLE IF EXISTS fruits;

CREATE TABLE fruits (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  color TEXT
);

DROP TABLE IF EXISTS cats;

CREATE TABLE cats (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  type TEXT,
  color TEXT
);

